#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:mysql://mamasdishdb.cpytqyofiryf.us-east-2.rds.amazonaws.com/MAMASDISH
spring.datasource.username=admin
spring.datasource.password=mamasdish123
spring.jpa.hibernate.ddl-auto=update

#email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pixelfoods24@gmail.com
spring.mail.password=mamasdish123

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# use TLS
spring.mail.properties.mail.smtp.starttls.enable=true
